### ISSUE TITLE
How to by pass antivirus

### ISSUE THREAD

**Issue by khuongnguyen77** [quasar/Quasar#1010]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
 - Server OS: [e.g. Windows 10]
 - Client OS: [e.g. Windows 7]
 - Server installed .NET Framework version: [e.g. v4.8]
 - Client installed .NET Framework version: [e.g. v4.8]
 - Quasar Version: [e.g. 1.3.0 or commit-id]
 - Build configuration: [e.g. Debug/Release]

**Additional context**

**Comment by gooduser1999** [comment]
I was able to bypass antivirus by injecting an aes encrypted loader containing the exe from the builder into a process like explorer.  I hope nobody posts code, you should do any weaponizing yourself.  Im assuming your redteaming because you obviously could just add an exception to windows defender under 'add or remove exclusions'.

**Comment by ErickDaGamer** [comment]
Check out issue #983.
