### ISSUE TITLE
Quasar.exe is not found

### ISSUE THREAD

**Issue by Dantanorrr** [quasar/Quasar#1054]
I tried to donwload Quasar and had to download visual studios in order to build and compiled the file to run it but as soon as i compile the file a erros shows up "The debug executable
'C:\Users\***\Desktop\RAT\Quasar\bin\Debug\net452\Quasar.exe' specified in the 'Quasar.Server' debug profile does not exist " can anyone please help?
There's not even a bin in the downloaded zip, i have tried every posible version but same problem, how can i fix this?

**Comment by ErickDaGamer** [comment]
Did you compile it in debug mode?

**Comment by Dantanorrr** [comment]
how do i check that?

**Comment by Dantanorrr** [comment]
I tried i on Release but same problem, the problem is that there is no bin folder in the download, no wonder he can't find the quasar.exe i think its a problem with the download file

**Comment by BurntDog** [comment]
This has been answered several time before. Please do a complete search using our search feature before posting, you'll most likely find a answer quicker then waiting for a response.

Thank you

**Comment by Dantanorrr** [comment]
can i please send me a link of the issue, i have searched for a solve but i didnt find anything

**Comment by ErickDaGamer** [comment]
Did you just compile Quasar.Server and not the whole solution? You are supposed to compile the entire solution.

**Comment by Dantanorrr** [comment]
i compiled the entire solution

**Comment by BurntDog** [comment]
> can i please send me a link of the issue, i have searched for a solve but i didnt find anything

Did you Turn OFF Windows Defender/or other Anti Virus or make a exclusion for the  Quasar-Master Folder  within Windows Defender? Windows Defender will turn itself back on after a while at least it has done that to me several times. Which is why putting Quasar sever .exe and the Client.exe along with the folder you are building/Compiling it in in Windows or whatever Anti Virus software you're using exclusion list to avoid being scanned and deleted.
