### ISSUE TITLE
Eset Antivirus Popup

### ISSUE THREAD

**Issue by kemalmeler** [quasar/Quasar#1098]
Eset detects "client.bin" file as a threat.
![image](https://user-images.githubusercontent.com/17831255/194826715-7832efcb-250a-46ce-a2e6-2a508c4440bd.png)

**Comment by MaxXor** [comment]
Known false positive.

See one of the various other reports: https://github.com/quasar/Quasar/issues?q=is%3Aissue+antivirus+is%3Aclosed

**Comment by BurntDog** [comment]
Ok, please understand that this is a free and opensource project that changes often. There is no way to have it green listed as approved so AV doesn't get set off. Do to it's capabilities it shows up as a trojan or hacker tool ect. As long as you get ALL the files from here it is safe to use and have on your system. It's opensource so you can look at all the code before compiling and change it at will yourself if you so choose (Just don't redistribute it under a different name because then you would be in violation of the license).

**Comment by kemalmeler** [comment]
I understand. I just wanted to flag. Thanks for quick response.
