### ISSUE TITLE
Fun Menu & Remote Michrophone and Remote camera please

### ISSUE THREAD

**Issue by samiemrepr** [quasar/Quasar#1117]
I want you to add remote michrophone, remote camera and fun menu please.
I want to prank people :D

**Comment by ErickDaCoder** [comment]
remote microphone and remote camera were both removed due to security concerns (see issue #899)
From the README: "Quasar is a fast and light-weight remote administration tool coded in C#. The usage ranges from user support through day-to-day administrative work to employee monitoring." I don't think you're supposed to prank employees.
