### ISSUE TITLE
Remote Microphone Implemented

### ISSUE THREAD

**Issue by ValonK** [quasar/Quasar#556]
Im following this project for a while now always a quite reader :) In my version of Quasar ive finished building remote microphone using https://github.com/naudio/NAudio . Is anybody interested so i could commit.

**Comment by DragonzMaster** [comment]
You can fork this repo and add your changes then send a pull request, So when @MaxXor finishes his studying can merge it or anyone else can add this change to his fork too.

**Comment by ValonK** [comment]
Ok thanks i will do that. :)

**Comment by igromanru** [comment]
It would be better, if someone start take care of the project in another fork and we will keep work there until @MaxXor come back.

**Comment by MaxXor** [comment]
I don't think anyone need to take care of this project as I will still merge well tested PRs and critical fixes. It's very stable as of now and I don't think this will change anytime soon.

**Comment by KX-Reaper** [comment]
Awsome! Great that you are willing to share your work with the community.

**Comment by ValonK** [comment]
Ive commited the Remote Microphone Feature. Work really well tested on 20 machines.

**Comment by DragonzMaster** [comment]
Nice work @ValonK .
Want to mention that 1 channel (mono) audio is fine for VOIP so we don't really need 2 channels (they only double the bandwidth used) unless the remote computer has microphone array ( double microphone like what I have in my laptop).
So It would be nice if we can choose the sample rate starting from 8khz up to 48khz and using 16 bit depth.
These tips are taken from an article on codeproject which is written by NAudio owner, if you have time you can take a look at the article. It can be found here : https://www.codeproject.com/articles/501521/how-to-convert-between-most-audio-formats-in-net

**Comment by ValonK** [comment]
Thanks! yeah im a github noob so i think i will give you a download link to the project :) is that ok?

**Comment by DragonzMaster** [comment]
Yup, that will be fine and then it will be available for anyone else want to see the code.

**Comment by ValonK** [comment]
http://www116.zippyshare.com/v/gSnAigrD/file.html  let me know what you think :) and what can be improved!

**Comment by DragonzMaster** [comment]
Great Job @ValonK .
I have cleaned up NAudio code so it is really smaller now (about 60KB added to client) instead of ~350KB .
First : You can replace NAudio files with these files in ZIP file below.
Second : You can change "channels" at audio packet to simple rate and change that combobox also in Microphone form (FrmMicrophone) and add these values : 
8000, 11025, 16000, 22050, 32000, 44100, 48000
all of them 16-bit depth and mono (1 Channel), feel free to add 2-Channel support.

Go to "AudioHandler.cs" in client and change this line:
`var waveFormat = new WaveFormat(44100, command.Channels);`
To
`var waveFormat = new WaveFormat(command.rate,16,1);`

[NAudio Cleaned](http://www.filedropper.com/naudio) / [Mirror](http://s000.tinyupload.com/index.php?file_id=74737560911854711261)

**Comment by ValonK** [comment]
Wow thanks for the Amazing feedback☺ Thanks for the size reducing and code clean up👍. I was worried because of the size! I will asap fork and add your Changes to my Repo.

**Comment by DragonzMaster** [comment]
You are welcome. 😄 
Want to remind you to make these changes on a NEW fork not the same one.
(you can delete your existent fork and re-fork again)

**Comment by ValonK** [comment]
oh thanks for the info. im currently reforking :) and adding your changes :)

**Comment by ValonK** [comment]
Ok fixed everything youve said :) Works like charm :) thanks again for the size reducing ! Should be available at my fork now.

**Comment by DragonzMaster** [comment]
First, I want to thank you for your efforts. But unfortunately you didn't get my point of adding the changes to NEW fork.
I meant that you don't add the old changes to a commit again but just push all the new work in one commit to original code from this repo. I can guess that you just don't know how to do this but I think it can be done by downloading Quasar master branch again and work on it INSTEAD of working on the copy on your PC.

Another time you have changed the client settings ( IP:port) 😛 

I've tested it with another simple rates (22kHz, 16kHz) but it seams to be not working as expected, I will look into this.

**Comment by ValonK** [comment]
Do you have skype ? or some kind of chat app? i would like to speak to you?

**Comment by DragonzMaster** [comment]
Only using Wire.

**Comment by ValonK** [comment]
ok add me  valon.k@outlook.at

**Comment by Lavarp** [comment]
Hi ! 

I have tried you Quasar version. I have installed it on a VPS and I cannot use the mic recording function... 
See my error :

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
xServer.Core.NAudio.Wave.MmeInterop.MmException: BadDeviceId calling waveOutOpen
   at xServer.Core.NAudio.Wave.WaveOutputs.WaveOut.Init(IWaveProvider waveProvider)
   at xServer.Forms.FrmMicrophone.InitializeNAudio()
   at xServer.Forms.FrmMicrophone..ctor(Client c)
   at xServer.Forms.FrmMain.remoteMicrophoneToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************


Have you any idea?

**Comment by ValonK** [comment]
Ive tested the Remote mic on 50+ windows Machines but i didnt test on a VPS. 
xServer.Core.NAudio.Wave.MmeInterop.MmException: BadDeviceId calling waveOutOpen
 The device that you are trying to listen to doesnt work or seems corrupt. Never had this exception before.

**Comment by daydreamermk** [comment]
ValonK,

How is it possible to use your version of the Client and Server?

Can you share it as a zip file ?

Thank you in advance.

**Comment by ValonK** [comment]
go to my github profile and download the fork of qasar. 
https://github.com/ValonK/QuasarRAT

**Comment by daydreamermk** [comment]
ValonK,

Thank you for your advice. However, I am using Visual Studio 2015 and run the project. I managed to build, but unable to see hosts although when using the stable release 1.3.0.0, i see them immidiatelly. 
Can you advise what is the problem ? Do i need to upload a new server, built with your fork or ?

Thank you in advance.

**Comment by ValonK** [comment]
Hmm i only added Remote Mic and nothing else so i dont understand why you get connection issues?
ive got only positive Response from people. 

Download my fork and Rebuild. I cant see what setup your using so helping you would be difficult.

**Comment by DragonzMaster** [comment]
You have one bug as I remember just check Wire, @ValonK . T
he WaveOut MUST be the same as WaveIn on remote PC so you have to change WaveFormat to the selected one from Combobox for both WaveIn & WaveOut.

**Comment by ValonK** [comment]
@DragonzMaster thanks for the Information.
 I will continue to fix and make improvements friday starting. Vacation Time :)

**Comment by FADDD** [comment]
ValonK I have an old version of Quasar how to install this thing?
Explain step by step, thank you very much
I tried, but as option did not work and the client disappeared

**Comment by badmanbh** [comment]
It's possible download a build of quasar with microphone feature ?

**Comment by ValonK** [comment]
Of course it's on my page

**Comment by badmanbh** [comment]
I'm new in github. I tried to fork your project, but the download is only the source-code.

**Comment by ValonK** [comment]
With the source code build it in visual studio. I will try to build it when I have time

**Comment by Anawaz** [comment]
I also get this exception on VPS.

xServer.Core.NAudio.Wave.MmeInterop.MmException: BadDeviceId calling waveOutOpen

**Comment by Abdullah2993** [comment]
do you have audio on your VPS?

**Comment by 77Dann** [comment]
Valonk could you upload the version Quasar RAT with remote microphone? I'm in a lot of need and your repository does not exist anymore.

**Comment by XYDsoft** [comment]
@ValonK “Hold to” Test null and void ！

**Comment by AleGor1902** [comment]
Valonk please! Can you upload Quasar RAT with microphone! I'm in a lot of need. Your repository does not exist anymore!!!

**Comment by jonrules48** [comment]
Hello, Sorry a little late but does anyone still need Quasar with microphone?

**Comment by XstreamBFI** [comment]
yes

**Comment by jonrules48** [comment]
https://github.com/quasar/QuasarRAT/tree/b2c6aabcabf8bc24929d2b05393d24f236d94659

**Comment by jonrules48** [comment]
although it is a bit buggy, but works
