### ISSUE TITLE
A webcam live view and microphone live remote 

### ISSUE THREAD

**Issue by naxceW** [quasar/Quasar#942]
It can be added live preview mice and cam?

**Comment by FarewellAngelina** [comment]
Webcam live existed in 1.3.0.0 , i saw no mention of why the removal of it in 1.4.0.0 , does it have something to do with future plugin support?

I could make a pull request of this feature but since it got removed i wanna know if this is warranted or not.

Also, microphone capture would be good, maybe using NAudio ? I used it a few years ago and it was somewhat decent... don't know if any improvements have been made on this functionality.

**Comment by gmiwoj** [comment]
get cam2ip - [https://github.com/gen2brain/cam2ip](https://github.com/gen2brain/cam2ip)

get nircmd -  [https://www.nirsoft.net/utils/nircmd.html](https://www.nirsoft.net/utils/nircmd.html)

upload to target pc somewhere 

run hidden cam2ip task using remote command like this: 
` "FULLPATH\nircmd.exe" exec hide "FULLPATH\cam2ip.exe"`

over LAN you can watch cam  stream in your browser or vlc like this: 
`http://TARGET_IP:56000/mjpeg`

getting access to target ip over the internet is more tricky

i use free ZeroTier service, it can create vpn bridge between you and target pc, but first you have to install, configure and hide zerotier app on target pc. there are other ways to do this, i use it because it's free, easy to setup and it works.

i havent tried getting sound yet, but i bet i can be done similar way

**Comment by LokeYourLord** [comment]
Yeah I was also wanting the Remote Audio feature, practically the only thing missing in Quasar, Webcam is too easily detectable anyways so not a feature I am desperate for.

**Comment by MaxXor** [comment]
Sorry accessing the desktop and the whole computer is powerful enough for a remote ADMINISTRATION tool. No need to directly spy on the user.

**Comment by LokeYourLord** [comment]
@MaxXor I wasn't wanting Webcam anyways, but is Audio possible? It would go along well with the RDP feature for seeing the Desktop.

**Comment by MaxXor** [comment]
Okay, but there is an issue for system audio already: https://github.com/quasar/Quasar/issues/135
