### ISSUE TITLE
connection is lost when restarting pc unless making an exclusion for a process

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [quasar/Quasar#967]
when i infect a system, then restart it, it removes the startup process, making it unable to reconnect unless you add a process exclusion in windows defender

**Comment by BurntDog** [comment]
Yes, you need to add exclusion in Windows Defender this is not a bug. Adding a exclusion should not be a issue because you're running the client on a system you have permission to. We don't use the word "infect" cause that is a term that is used when committing a illegal act, and that is not the intent of this tool.
