### ISSUE TITLE
automatically intercepted by anti-virus software

### ISSUE THREAD

**Issue by QAQ5555** [quasar/Quasar#990]
Quasar is used as a backdoor program and is automatically intercepted by anti-virus software. Is it possible to add functions such as code obfuscation?

**Comment by BurntDog** [comment]
You should only be using it on systems you have permission. You can add it to the Antivirus exclusion list or if you know what you're doing there are ways to make it less detectible but, we don't get into that discussion here mainly because the intention and use of this tool is for legit and legal use. But, because some will still try to use it in the wrong way (without permission) MaxXor, the person in charge of it's code and the entire project won't be part of any misuse.
